/* eslint-disable quotes */
export const BOOK_COUNT_PER_PAGE = 8;

export const BOOKS = [
	{
		key: 'pop-up',
		title: 'Pop Up Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 3,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 2,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
	{
		key: 'paper',
		title: 'Paper Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
	{
		key: 'jigsaw',
		title: 'Jigsaw Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
	{
		key: 'story',
		title: 'Story Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
	{
		key: 'puzzle',
		title: 'Puzzle Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
	{
		key: 'atlas',
		title: 'Atlas Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
	{
		key: 'light',
		title: 'Light Book',
		books: [
			{
				name: 'The Happy Lemon',
				rate: 5,
				author: 'Kurt Yamashita',
				slug: 'the-happy-lemon',
				image: '/assets/images/b1.jpg',
			},
			{
				name: 'Crocodile: The Journey',
				rate: 4,
				author: 'Henrietta Mitchell',
				slug: 'crocodile-the-journey',
				image: '/assets/images/b2.jpg',
			},
			{
				name: 'Journey To The Stars',
				rate: 5,
				author: 'Matt Zhang',
				slug: 'journey-to-the-stars',
				image: '/assets/images/b3.jpg',
			},
			{
				name: 'Lovely Family',
				rate: 5,
				author: 'Olivia Wilson',
				slug: 'lovely-family',
				image: '/assets/images/b4.jpg',
			},
		],
	},
];

export const BLOGS = [
	{
		title: "10 Fun and Creative Ways to Encourage Your Child's Love of Reading",
		author: 'WaiBook',
		date: '06 July 2022',
		image: '/assets/images/c4.jpg',
		slug: 'blog-1',
	},
	{
		title: "The Power of Representation: Why Diverse Children's Books Matter",
		author: 'WaiBook',
		date: '06 July 2022',
		image: '/assets/images/c5.jpg',
		slug: 'blog-2',
	},
	{
		title: "From Page to Screen: Exploring the World of Children's Book Adaptations",
		author: 'WaiBook',
		date: '06 July 2022',
		image: '/assets/images/c6.jpg',
		slug: 'blog-3',
	},
];
